### ISSUE TITLE
can't find the config file and policy code

### ISSUE THREAD

**Issue by suk063** [renyu2016/Generalized-3D-Manipulation#1]
Hi, thanks for the nice work.

I want to try running your code, but I don't see the gdp3 config file in repo (I only see dp3.yaml ). Also, the policy code file.
Could you share more detail instruction to run your code?

Thanks

**Comment by renyu2016** [comment]
Hi, thank you for your interest! The code is based on the DP3 framework. We forgot to update the names of the dp3.yaml and dp3.py files, but you can use them as they are. The main differences between our method and DP3 lie in the tracking of target objects, the reference frame selection for the point cloud, and the data augmentation in dataset.py. Therefore, the differences in the configuration and policy files are minimal.
