### ISSUE TITLE
Problem about evaluation

### ISSUE THREAD

**Issue by 19373254** [renyu2016/Generalized-3D-Manipulation#3]
Thank you for your insightful paper. When I run bash GDP3/train_policy.sh gdp3 metaworld_soccer 0112 0 0 and the code enters the eval stage, the program would stuck like this:
![image](https://github.com/user-attachments/assets/4065346f-9d16-42a4-a966-56ebdc677a32)
I appreciate it if you can give me some advice. Thanks.

**Comment by renyu2016** [comment]
Hi, when evaluating the policy, you should also segment the target objects in the first frame. Just like the same process used during data collection. Please ensure that the order of segmentation matches the order used in the data collection process.
